---
title: "Free evolution of Hermite functions"
author: "Akshay Shankar"
date: "2025-12-05"
categories: [chunk, bec, quantum]
draft: true
---

$$
\begin{align}
    \bra{x}\hat\rho(t_0 + t_h + t_t)\ket{x} &= \bra{x}e^{-\frac{iH_0 t_t}{\hbar}} \hat \rho(t_0 + t_h) e^{\frac{iH_0t_t}{\hbar}}\ket{x}\\
     &= \int dp \int dp' \, e^{-\frac{ip^2 t_t}{2m\hbar}} \bra{p}\hat \rho(t_0 + t_h) \ket{p'}e^{\frac{ip'^2t_t}{2m\hbar}} \braket{x|p}\braket{p'|x}\\
    &= \frac{1}{2\pi\hbar}\int dp \int dp' \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}} \bra{p}\hat \rho(t_0 + t_h) \ket{p'}e^{\frac{ip'^2t_t}{2m\hbar} - \frac{ip'x}{\hbar}}\\
    &= \frac{1}{2\pi\hbar}\sum_{\lambda, \lambda'}\int dp \int dp' \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}} \braket{p | \lambda}\bra{\lambda}\hat \rho(t_0 + t_h)\ket{\lambda'} \braket{\lambda'| p'}e^{\frac{ip'^2t_t}{2m\hbar} - \frac{ip'x}{\hbar}}\\
    &= \frac{1}{2\pi\hbar}\sum_{\lambda, \lambda'}\left (\int dp \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}} \braket{p | \lambda} \right ) \left (\int dp' \braket{\lambda'| p'}e^{\frac{ip'^2t_t}{2m\hbar} - ip'x}\right) \cdot \bra{\lambda}\hat \rho(t_0 + t_h)\ket{\lambda'}\\
    &=\frac{1}{2\pi\hbar}\sum_{\lambda, \lambda'}\left (\int dp \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}} \braket{p | \lambda} \right ) \left (\int dp' \braket{\lambda'| p'}e^{\frac{ip'^2t_t}{2m\hbar} - \frac{ip'x}{\hbar}}\right) \cdot \bra{\lambda}\hat \rho(t_0)\ket{\lambda'} \, e^{i\omega t_h (\lambda' - \lambda)}\\
    &= \sum_{\lambda, \lambda'} f(x, \lambda, \lambda', t) \cdot \rho_{\lambda, \lambda'}(t_0) \cdot \exp{i\omega t_h (\lambda' - \lambda)}
\end{align}
$$
Where now have,
$$
\begin{equation}
    \braket{p|\lambda} = \int dx \, \braket{p|x}\braket{x|\lambda} = \frac{1}{\sqrt{2\pi\hbar l_h}}\int dx \, e^{-\frac{ipx}{\hbar}} h_{\lambda}(x/l_h)    
\end{equation}
$$
where $h_{\lambda}(x)$ is the Hermite function defined as follows in terms of the Hermite polynomials $H_{\lambda}(x)$,
$$
\begin{equation}
h_{\lambda}(x) = \frac{1}{\pi^{1/4}\sqrt{2^n n!}} H_{\lambda}(x) e^{-x^2/2}  
\end{equation}
$$
It is known that the Hermite functions are eigenvectors of the Fourier transform operation,
$$
\begin{align}
\frac{1}{\sqrt{2\pi}}\int dx \, e^{-ikx} h_{\lambda}(x) = (-i)^{\lambda} h_{\lambda}(k)
\end{align}
$$
So in our case, we have 
$$
\begin{align}
    \int dx \, \braket{p|x}\braket{x|\lambda} &= \frac{1}{\sqrt{2\pi\hbar l_h}}\int dx \, e^{-\frac{ipx}{\hbar}} h_{\lambda}(x/l_h)\\
    &= \sqrt{\frac{l_h}{\hbar}} (-i)^{\lambda} h_{\lambda}(pl_h/\hbar)
\end{align}
$$
The integral is then,
$$
\begin{align}
    &=\int dp \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}} \braket{p | \lambda}\\
    &=\sqrt{\frac{l_h}{\hbar}} \int dp \, e^{-\frac{ip^2 t_t}{2m\hbar} + \frac{ipx}{\hbar}}(-i)^{\lambda} h_{\lambda}(pl_h/\hbar) \\
\end{align}
$$
Changing variables $z = pl_h/\hbar$,
$$
\begin{align}
    &= (-i)^{\lambda} \sqrt{\frac{l_h}{\hbar}} \, \frac{\hbar}{l_h} \int dz\, \exp{\left( i\left(-\frac{t\hbar}{2ml_h^2} z^2 + \frac{x\hbar}{\hbar l_h}z\right)\right )} h_{\lambda}(z)\\
    &= (-i)^{\lambda} \sqrt{\frac{\hbar}{l_h}} \int dz \, \exp{\left(i\left( -\frac{1}{2}\omega t_t z^2 + \frac{x}{l_h} z\right)\right)} h_{\lambda}(z)
\end{align}
$$
The function required can be written as 
$$
\begin{align}
f(x, \lambda, \lambda', t) = (-i)^{\lambda}(i)^{\lambda}\frac{1}{2\pi l_h}J_{\lambda}\bar J_{\lambda'}    
\end{align}
$$
We then require the following integral to proceed (which is the generic form of $J_n$ as introduced above),
$$
\begin{equation}
    I_n = \int_{-\infty}^{\infty} dx \, h_n(x) \, e^{i(Ax^2 + Bx)}     
\end{equation}
$$
where $h_n(x)$ are the physicist's Hermite functions defined in terms of the Hermite polynomials $H_n(x)$ as follows,
$$
\begin{equation}
    h_n(x) = \frac{1}{\pi^{1/4} \sqrt{2^n n!}} H_n(x) \, e^{-x^2/2}
\end{equation}
$$
We also know that the Hermite polynomials can be written in terms of a generating function, 
$$
\begin{equation}
    e^{2xt - t^2} = \sum_{n=0}^{\infty} \frac{H_n(x)}{n!} t^n
\end{equation}
$$
We may then write a similar generating function for the Hermite functions,
$$
\begin{equation}
    e^{2xt - t^2 - \frac{x^2}{2}} = \sum_{n=0}^{\infty}h_n(x)\, \pi^{1/4} \sqrt{\frac{2^n}{n!}} \, t^n    
\end{equation}
$$
Multiplying the integrand on both sides and integrating over $x$, we get,
$$
\begin{equation}
    \int_{-\infty}^{\infty} dx \, e^{2xt - t^2 - \frac{x^2}{2}} \cdot e^{iAx^2 + iBx} = \sum_{n=0}^{\infty} I_n \, \pi^{1/4} \sqrt{\frac{2^n}{n!}} \, t^n
\end{equation}
$$
We now evaluate the integral on the left,
$$
\begin{align}
    &= \int_{-\infty}^{\infty} dx \, e^{(iA - \frac{1}{2})x^2 + (2t + iB)x - t^2}\\
\end{align}
$$
which is a gaussian integral of form
$$
\begin{align}
    &= \int_{-\infty}^{\infty} dx \, e^{Ex^2 + Fx + G}\\
    &= e^{G - \frac{F^2}{4E}} \int_{-\infty}^{\infty} dx \, e^{E(x + \frac{F}{2E})^2}\\
    &= e^{G - \frac{F^2}{4E}} \int_{-\infty}^{\infty} du \, e^{Eu^2}
\end{align}
$$
Since $Re(E) < 0$, this integral converges even for complex coefficients,
$$
\begin{align}
    &= e^{G - \frac{F^2}{4E}} \sqrt{\frac{\pi}{-E}}\\
    &= \sqrt{\frac{\pi}{1/2 - iA}} \exp{\left( -t^2 - \frac{(iB + 2t)^2}{4iA - 2} \right)}\\
    &= \sqrt{\frac{2\pi}{1 - 2iA}} \exp{\left(\frac{-(4iA + 2)t^2 - 4iBt + B^2}{4iA - 2} \right)}\\
    &= \sqrt{\frac{2\pi}{1 - 2iA}} \exp{\left(\frac{-B^2}{2(1 - 2iA)}\right)} \exp{\left(\frac{(1 + 2iA)}{1 - 2iA} t^2 + \frac{2iB}{1 - 2iA} t \right)}
\end{align}
$$
This is of the same form as the generating polynomial for the Hermite polynomials, which can be generalized like so. The physicist's Hermite polynomials \(H_n(x)\) have the generating function
$$
\begin{equation}
e^{2 x t - t^2} = \sum_{n=0}^{\infty} H_n(x) \frac{t^n}{n!}.
\end{equation}
$$
We want to express \(e^{u t^2 + v t}\) in terms of \(H_n(x)\). We start by rewriting the exponential:
$$
\begin{align}
e^{u t^2 + v t} 
&= e^{-(\sqrt{-u}\, t)^2 + v t}.
\end{align}
$$
Comparing with the generating function, we set
$$
\begin{equation}
2 x (\sqrt{-u}\, t) = v t \quad \Rightarrow \quad x = \frac{v}{2 \sqrt{-u}}.
\end{equation}
$$
Thus, the expansion in terms of Hermite polynomials is
$$
\begin{align}
e^{u t^2 + v t} 
&= \sum_{n=0}^{\infty} H_n\Big(\frac{v}{2\sqrt{-u}}\Big) \frac{(\sqrt{-u}\, t)^n}{n!} \\
&= \sum_{n=0}^{\infty} \frac{(\sqrt{-u})^n}{n!} H_n\Big(\frac{v}{2\sqrt{-u}}\Big) t^n,
\end{align}
$$
which holds for complex \(u\) by taking the principal complex square root \(\sqrt{-u}\).

Now, we match co-efficients with the right hand side of Equation 40.
$$
\begin{align}
    I_n \pi^{1/4} \frac{\sqrt{2^n}}{\sqrt{n!}} &=  \sqrt{\frac{2\pi}{1 - 2iA}} \exp{\left(\frac{-B^2}{2(1 - 2iA)}\right)} \frac{(\sqrt{-u})^n}{n!} H_n\left (\frac{v}{2\sqrt{-u}} \right )\\
    I_n &=  \frac{1}{\pi^{1/4}\sqrt{2^n n!}}\sqrt{\frac{2\pi}{1 - 2iA}} \exp{\left(\frac{-B^2}{2(1 - 2iA)}\right)} \left(\frac{(2iA + 1)}{(2iA - 1)}\right)^{n/2} H_n\left (\frac{B}{\sqrt{1+4A^2}}\right )\\
\end{align}
$$
Or in terms of the Hermite functions, 
$$
\begin{align}
I_n &= 
\sqrt{\frac{2\pi}{(1-2iA)}} \, \left(\frac{(2iA + 1)}{(2iA - 1)}\right)^{n/2} \, \exp\Bigg(\frac{-B^2}{2(1-2iA)} + \frac{B^2}{2(1+4A^2)}\Bigg) \,
h_n\Bigg(\frac{B}{\sqrt{1+4A^2}}\Bigg)\\
&=\sqrt{\frac{2\pi}{(1-2iA)}} \, \left(\frac{(2iA + 1)}{(2iA - 1)}\right)^{n/2} \,
\exp\Bigg[-\frac{iB^2A}{1 + 4A^2}\Bigg] \,
h_n\Bigg(\frac{B}{\sqrt{1+4A^2}}\Bigg)
\end{align}
$$
where, we have $A = -\omega t_t/2$ and $B = x/l_h$.