project:
  type: website

execute:
  freeze: auto
  kernel: julia
  
website:
  title: "ResearchTidbits"
  site-url: https://20akshay00.github.io/ResearchTidbits/
  description: "A collection of concise ideas gathered while exploring many-body physics."
  open-graph: true    # standard for LinkedIn/Facebook/Slack
  twitter-card: true  # specific for Twitter
  google-analytics: 
    tracking-id: "G-361104V04L"
    storage: none
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/20akshay00
      - icon: twitter
        href: https://twitter.com/20akshay00
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - cosmo
      - brand
      - cerulean
    css: styles.css



