project:
  type: website

website:
  title: "ResearchTidbits"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/20akshay00
      - icon: twitter
        href: https://twitter.com/20akshay00
format:
  html:
    theme:
      - cosmo
      - brand
      - cerulean
    css: styles.css



